### ISSUE TITLE
Discussion: Ideas to mitigate sync issues for users when using /_notebooks or /_word

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fast_template#16]
The way the automation for `_word` and `_notebooks` work are the new files are pushed onto the master branch after the user pushes, which causes their local branch to get out of sync.  This understandably causes confusion.  For example, [see this tweet](https://twitter.com/cto_maverick/status/1222533248942776320?s=20)

![image](https://user-images.githubusercontent.com/1483922/73369667-d3298600-4267-11ea-9a0e-7b25bdde3a49.png)

I have an idea on how to mitigate this.  I could have GitHub Actions always keep the `gh-pages` branch updated automatically.  This would require pushing to `gh-pages` after each push or build.  This would require the following changes in the docs:

- We would have to add an additional step in the setup process where the user selects the `gh-pages` option. 
- Add some clarification in the docs on how this all works, for example a warning not to edit the `gh-pages` branch directly since that will get overwritten.  
- We could probably remove the `/sync` magic command from the commit messages as well  for `/_notebooks` since this may no longer be needed. 

Thoughts?  Is this a crazy idea?  This is assuming that people are working in their master branch or another branch and can safely ignore the `gh-pages`  branch.

**Comment by natikgadzhi** [comment]
I think simplifying the interaction for the users would be great! 

In terms of workflow, you suggest that the github action commits and pushes changes to `gh-pages` branch _instead_ of master, and that way, assuming the user works in master, they won't have to git pull constantly before pushing their changes, right? 

If the gh action builds _notebooks and _word and puts it in _posts in gh-actions branch, than it'll be important to always merge `master` into `gh-pages` before generating posts in the action script: 

1. User created the repo, there's no`gh-pages` branch yet. 
2. User adds a post to `_notebooks`, pushes it to production.
3. gh-action will have to pick up the post, convert it to `_posts`, **create the `gh-pages`** branch, and commit the converted post. `gh-pages` branch is now 1 commit ahead of `master`
4. User then writes another post in markdown, in `_posts`, commits and pushes that to origin. `master` now has 1 commit with that post that is not in `gh-pages`branch.
5. The gh-action script **will have to first rebase `gh-pages` from fresh `master` to make sure it has all the posts user wrote in `_posts`** there, and then — regenerate posts from `_notebooks` and `_word`, and push to `gh-pages` branch after that. 

That should work 🤔 This is just thinking out loud, I'm not an expert in github actions by any means.

Aside: not a suggestion on how to implement this, but an observation from my experience. 
1. I've moved things around a bit: renamed `_action_files` to scripts` and installed `nbdev` locally
2. I run python `scripts/nb2post.py` locally to have a local preview of my post that I write in a notebook. 
This flow won't be affected in any way if the gh-action builds pages in `gh-pages` branch.

**Comment by hamelsmu** [comment]
Thanks so much for helping me think through this!  It’s very helpful to have someone to sanity check ideas. 🙇 

~One thing I’m worried about is race conditions caused by someone updating different types of items (md, notebook, word) and a collision occurs causing a conflict.  And a conflict is something that really scares me because that’s when users who aren’t so technical will enter the “scary git zone” which is what this repo caters to.  I feel like there is a way to design for this scenario to minimize this but I would need to simulate it to be sure.~  

**Update**:  Another idea would be to do the build for the webpages (like you do locally) inside Actions and push the contents of the `_site` folder to the gh_pages branch.  That way, you don't have to do rebase etc?  There are some additional upsides:
 - we can include tools not supported by GH pages (because we are building ourselves) such as this one Jeremy told me about that [manages POST files](https://github.com/nhoizey/jekyll-postfiles).  
 - The build process will be less opaque and users will get a full stack trace if something breaks ( opposed to the sometimes cryptic error messages you get on the settings page )

Let me know if you have any thoughts or ideas for this scenario.  Thanks so much appreciate your input

**Comment by natikgadzhi** [comment]
I've written a few paragraphs and realized I'm confused and don't know what I'm talking about. 

I agree doing a full `jekyll build` in an action and then committing `_site` to `gh-pages` is the least confusing scenario: 
1. Don't have to manage any merge conflicts, just tell users to never commit anything  in `_site` to `gh-pages` directly. 
2. Much easier to understand, since the most build logic can be in a github action. We can make a separage gh action for this, and clearly name them to have several steps, like 01_convert_nbs, 02_convert_word, 03_build_jekyll. 
3. Doesn't add complexity for users: `gh-pages` branch will work by default without any extra settings. 

Bonus points for supporting newer themes, `minima`, for example, has a stable 3.0, but github pages is locked on 2.5.1.

**Comment by hamelsmu** [comment]
> I've written a few paragraphs and realized I'm confused and don't know what I'm talking about.

Don't be so hard on yourself.  I do this all the time 🙇   

User experience question:  we could make it so that the nb2md or word2md only be a temporary artifact that lives inside the Action which subsequently gets built, thus never materializing a .md file in _posts that is actually checked in (which also avoids local conflicts).  But is this bad?  Do you think users will want to see the intermediate .md file that is generated in _posts?  If we want to push converted .md files into master then we would still face the issue of local conflicts, but this is more transparent to the user ( I for one, would appreciate seeing these converted files, even if it means dealing with local conflicts - what about you? )

However, you may have convinced me that it is worth building the page ourselves despite the local conflicts persisting for the other reasons mentioned.  

Any additional thoughts that come to mind? 

BTW Where can I go to find release information about 3.0?  I can only find 2.5.1 [here](https://github.com/jekyll/minima/releases)?  Maybe I'm looking in the wrong place?

**Comment by natikgadzhi** [comment]
For my blog, I've set a local nbdev with a settings.ini and I convert nb2html and preview the results when I work on an article.So I'm with you on that part. 

There actually are two separate ideas I'd love to hear your thoughts on: 
1. Should we add an example `settings.ini` and `requirements.txt` so that we can clean up the gh-action code, and so that users can install `nbdev` and convert posts locally easier, without messing their repos too much, or is it too heavy for a more common, just-wanna-blog-with-github use case? I wanted to create a discussion issue on this, decided it's early, I'll finish the first PR first and then post on forums.
2. I actually want to write a small watcher / maybe a jekyll watcher plugin that would monitor `_notebooks/*.ipynb` for me, and re-run conversion nb2html every time I saved a notebook, i.e. live reload in local environment. I can share the code with you if you'd like that for yourself, or maybe we can add it as an option here.

(I think both are out of scope of this issue and I should probably go make a forum thread about those)

 > BTW Where can I go to find release information about 3.0? I can only find 2.5.1 here? Maybe I'm looking in the wrong place?

Which proves my point about not knowing what I was talking about. [Jekyll/minima Readme](https://github.com/jekyll/minima) mentions 3.0 release, but it's not in releases, and I've tried `gem install minima` — you're absolutely right, 2.5.1 seems to be the latest release. My bad. 🤦🏼‍♂️

**Comment by hamelsmu** [comment]
Ok I think you have good points and like you said it’s probably better to open a post on the forum to collect more feedback and ideas so I’ll go ahead and close this issue and open a forum thread instead.  

If it’s a bad idea to close this issue for some reason lmk can always reopen it
